config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only:[:create, :destroy]

  resources :charges

  resources :users

  resources :users do
    get '/login', to: 'users#login_test' # delete this before deployment
  end
# test index for cookie testing
get '/cookie', to: 'carts#cookie', as: 'cookie'

  resources :carts do 
    patch '/email_preferences', to: 'carts#email_preferences', as: 'email_preferences'
    patch '/text_preferences', to: 'carts#text_preferences', as: 'text_preferences'
  end




  

  namespace :carts do
    scope '/:cart_id' do
      # resource :products, only:[:new, :create]
      resources :products
      delete '/remove/:id', to: 'users#remove', as: 'remove_user'
      post '/invite', to: 'users#invite', as: 'invite_user'
    end

  end

  # resources :products

  get '/invite/:key', to: 'carts#invite', as: 'carts_invite'

  post 'refunds', to: 'refunds#create', as: 'refunds'

  # api
  namespace :api do
    resources :charges, only: [:create]
    resources :carts, only: [:index, :create, :invite, :show, :destroy] do 
      post '/users/invite', to: 'carts/users#invite'
    end
    resources :users, only: [:create]
  end

  post '/api/charges', to: 'charges#create'
  post '/api/carts/:id/products', to: 'api/carts/products#create'
  get 'api/carts/token/:token', to: 'api/carts#index'
  get '/api/carts/:id/:token', to:'api/carts#show'

  resources :sessions, only:[:create, :destroy]

  get 'auth/:provider/callback', to: 'omniauth_sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  # admin
  namespace :admin do
    resources :users
    resources :carts, only:[:index]
    resources :charges
  end

  root to: 'users#index'

end

app/views/navbar/_errors.html.erb
<div class="errors">
  <% if session[:errors] %>
    <div id="error_explanation">
      <h2>Some issues prohibited this user from being saved:</h2>
   
      <ul>
      <% session[:errors].each do |type, error| %>
        <% error.each do |e| %>
          <li><%= "#{type} #{e}" %></li>
        <% end %>
      <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/navbar/_full_navbar.html.erb
  <div id="user_nav">
    <% if current_user %>
     <%= render 'navbar/logged_in' %>
    <% else %>
     <%= render 'navbar/registration' %>
     <%= render 'navbar/login' %> 
     <%= link_to "Want to use Facebook?", "/auth/facebook", id: "sign_in" %>
    <% end %>
  </div>

  <%= render 'navbar/errors' %>
  <hr>

app/views/navbar/_logged_in.html.erb
 Signed in as <strong><%= current_user.name %></strong>!
<%= link_to "Sign out", signout_path, id: "sign_out" %>

app/views/navbar/_login.html.erb
<h3>Login</h3>
<%= form_tag sessions_path do %>
  <%= label_tag "Email" %>
  <%= text_field_tag :email, nil, { placeholder: @email } %> 
  <%= label_tag "Password" %>
  <%= password_field_tag :password %>
  <%= submit_tag "Submit" %>
<% end %>

app/views/navbar/_registration.html.erb
  <h3 class= "registration-title">Register</h3>
  <div>
    <%= form_for @user do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %> 
    <%= f.label :Email %>
    <%= f.text_field :email, placeholder: @email %> 
    <%= f.label :number %>
    <%= f.text_field :number %>
    <%= f.label :password %>
    <%= f.text_field :password %>
    <%= f.submit %>
    <% end %>
  </div>