config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only:[:create, :destroy]

  resources :charges

  resources :users

  resources :users do
    get '/login', to: 'users#login_test' # delete this before deployment
  end
# test index for cookie testing
get '/cookie', to: 'carts#cookie', as: 'cookie'

  resources :carts do 
    patch '/email_preferences', to: 'carts#email_preferences', as: 'email_preferences'
    patch '/text_preferences', to: 'carts#text_preferences', as: 'text_preferences'
  end




  

  namespace :carts do
    scope '/:cart_id' do
      # resource :products, only:[:new, :create]
      resources :products
      delete '/remove/:id', to: 'users#remove', as: 'remove_user'
      post '/invite', to: 'users#invite', as: 'invite_user'
    end

  end

  # resources :products

  get '/invite/:key', to: 'carts#invite', as: 'carts_invite'

  post 'refunds', to: 'refunds#create', as: 'refunds'

  # api
  namespace :api do
    resources :charges, only: [:create]
    resources :carts, only: [:index, :create, :invite, :show, :destroy] do 
      post '/users/invite', to: 'carts/users#invite'
    end
    resources :users, only: [:create]
  end

  post '/api/charges', to: 'charges#create'
  post '/api/carts/:id/products', to: 'api/carts/products#create'
  get 'api/carts/token/:token', to: 'api/carts#index'
  get '/api/carts/:id/:token', to:'api/carts#show'

  resources :sessions, only:[:create, :destroy]

  get 'auth/:provider/callback', to: 'omniauth_sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  # admin
  namespace :admin do
    resources :users
    resources :carts, only:[:index]
    resources :charges
  end

  root to: 'users#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :cart_roles
  has_many :carts, through: :cart_roles
  has_many :roles, through: :cart_roles
  has_many :payments
  has_many :refunds, through: :payments


  validates :name, presence: true
  # validates :email, presence: true, length: { minimum: 5 }
  validates :password, presence: true, length: { minimum: 8 }, on: :update, allow_blank: true

  has_secure_password


  def self.from_omniauth(auth)
    where(uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.email = auth.info.email
      user.image = auth.info.image
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.password = SecureRandom.uuid.to_s
      user.oauth_expires_at = auth.credentials.expires_at.nil? ? 7 : Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_filter :require_admin

  def index
    @users = User.all
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @users }
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_users_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to admin_users_path
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
  end

  protected

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/controllers/api/carts/users_controller.rb
class Api::Carts::UsersController < ApplicationController
 skip_before_action :verify_authenticity_token

  def current_user
    @current_user ||= User.find(params[:id]) unless params[:id].nil?
  end

 def remove
  @user = User.find(params[:id])
  @cart = Cart.find(params[:cart_id])
  deleted_user = CartRole.find_by(user_id: @user.id, cart_id: @cart.id)
  if deleted_user.destroy
    Notifications.delete_contributor(@user, @cart).deliver_now
    # Do we need to create a notification row for this?
  end
  redirect_to cart_path(@cart)
  end

  def invite
    #THE RIGHT ONE
      @inviter = current_user
      @cart = Cart.find(params[:cart_id])
      @email = params[:email]
      # @emails.each do |key, email|
        Notifications.invite_contributor(@inviter, @cart, @email).deliver_now
        # Do we need to create a notification row for this?
      # end 
      render :json => { message: "Hey buddo, your invitation was sent successfully."}, status: 200
  end

  protected

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/controllers/api/users_controller.rb
class UsersController < ApplicationController

  def update
    # @cart = Cart.find(session[:cart_id])
    @user = CartRole.find_by(user_id: params[:user_id], cart_id: params[:cart_id])
    # @user.password = SecureRandom.uuid
    @user.update_attributes()
    if @user.save
      # @cart = Cart.find(session[:cart_id])
      render :json => {
        user: @user.as_json(include: :carts)
      }
    else

    end
  end

end

app/controllers/carts/users_controller.rb
class Carts::UsersController < ApplicationController
 skip_before_action :verify_authenticity_token


 def remove
  @user = User.find(params[:id])
  @cart = Cart.find(params[:cart_id])
  deleted_user = CartRole.find_by(user_id: @user.id, cart_id: @cart.id)
  if deleted_user.destroy
    Notifications.delete_contributor(@user, @cart).deliver_now
    # Do we need to create a notification row for this?
  end
  redirect_to cart_path(@cart)
  end

  def invite
      @inviter = current_user
      @cart = Cart.find(params[:cart_id])
      @email = params[:email]
      # @emails.each do |key, email|
        Notifications.invite_contributor(@inviter, @cart, @email).deliver_now
        # Do we need to create a notification row for this?
      # end 
      render :json => { message: "Hey #{@inviter.name}, your invitation to #{@email} was sent successfully."}, status: 200
  end

  protected

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/controllers/users_controller.rb
require 'securerandom'
class UsersController < ApplicationController
  def index
    @user = User.new
    render :index
  end

  def create
    @user = User.new(user_params)
    if @user.save 
      Notifications.welcome_email(@user).deliver_now
            if session[:key]
        key = session[:key]
        session[:key] = nil
        CartRole.create(user_id: @user.id, cart_id: key, role_id: 2, email_notifications: true, text_notifications: true)
        # Will only redirect users to the invite page IF that is how 
        # they reached the site in the first place

        redirect_to "http://localhost:3000/dashboard/?token=#{@user.id}"
      else
        redirect_to "http://localhost:3000/dashboard/?token=#{@user.id}"
      end
    else
      redirect_to root_path
    end
  end


  def destroy
  end

  def login_test
    cookies[:user_name] = User.find(params[:user_id]).name
    cookies[:user_id] = params[:user_id]
    session[:user_id] = params[:user_id]
    redirect_to "http://localhost:3000/dashboard?token=#{params[:user_id]}"
  end



  protected

  def user_params
    params.require(:user).permit("name", "email", "password", "number")
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_newCart.html.erb
  <%= form_for @cart, url: carts_path(@cart) do |f| %>
  <%= f.label "Name" %>
  <%= f.text_field :name %> 
  <br>
  <%= f.label "Minimum Payment" %>
  <%= f.number_field :minimum_payment %>
  <br>
  <%= f.label "Due Date" %>
  <%= f.date_field :expiry %>
  <br>
  <%= f.submit "Submit" %>
  <% end %>

app/views/users/_new_cart.html.erb
  <%= form_for @cart, url: carts_path(@cart) do |f| %>
  <%= f.label "Name" %>
  <%= f.text_field :name %> 
  <br>
  <%= f.label "Due Date" %>
  <%= f.date_field :expiry %>
  <br>
  <%= f.submit "Submit" %>
  <% end %>

app/views/users/index.html.erb
<section id="hero">
  <a href="/dashboard" class="logo">
    <img src="http://i.imgur.com/pk4uMob.png" /><h1>Tucan</h1>
  </a>
  <div class="sign-in-btn">
    <a class="waves-effect waves-light btn btn-secondary modal-trigger" href="#sign-in-modal">Sign In</a>
  </div>
  <div class="cta">
    <h1>Buy products online. <br/>Split the cost between friends.</h1>
    <a class="btn-rect btn-primary waves-effect waves-light modal-trigger" href="#sign-up-modal">GET STARTED</a>
  </div>
  <div class="overlay"></div>

  <!-- sign up modal -->
  <div id="sign-up-modal" class="modal">
    <div class="modal-header">
      <h4>Sign Up</h4>
      <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat"><i class="material-icons">clear</i></a>
    </div>
    <div class="modal-content center-align">
      <a target="_blank" href="/auth/facebook">
      <button class="btn btn-facebook waves-effect waves-light" type="submit" name="action">
        <i class="fa fa-facebook-square" aria-hidden="true"></i> Connect with Facebook
      </button>
      </a>
    </div>
    <div class="modal-content">
      <div class="row">
        <%= form_for @user do |f| %>
          <!-- name field -->
          <div class="row">
            <div class="input-field col s12">
              <%= f.text_field :name %>
              <label for="name">Full name</label>
            </div>
          </div>
          <!-- email field -->
          <div class="row">
            <div class="input-field col s12">
              <%= f.text_field :email %>
              <label for="email">Email</label>
            </div>
          </div>
          <!-- phone field -->
          <div class="row">
            <div class="input-field col s12">
              <%= f.text_field :number %>
              <label for="email">Phone</label>
            </div>
          </div>
          <!-- password field -->
          <div class="row">
            <div class="input-field col s12">
              <%= f.password_field :password %>
              <label for="password">Password</label>
            </div>
          </div>
          <div class="row">
            <div class="col s12 right-align">
              <button class="btn waves-effect waves-light" type="submit" name="action">Sign up
                <i class="material-icons right">send</i>
              </button>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="modal-footer center-align">
      <p>By signing up you agree to our Terms of Use and Privacy Policy.</p>
    </div>
  </div>

  <!-- sign in modal -->
  <div id="sign-in-modal" class="modal">
    <div class="modal-header center-align">
      <h4>Sign In</h4>
      <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat"><i class="material-icons">clear</i></a>
    </div>
    <div class="modal-content center-align">
      <a href="/auth/facebook">
      <button class="btn btn-facebook waves-effect waves-light" type="submit">
        <i class="fa fa-facebook-square" aria-hidden="true"></i> Connect with Facebook
      </button>
      </a>
    </div>
    <div class="modal-content">
      <div class="row">
        <%= form_tag(sessions_path, method: "post", class:"col s12") do %>
          <!-- email field -->
          <div class="row">
            <div class="input-field col s12">
              <%= text_field_tag :email %>
              <label for="email">Email</label>
            </div>
          </div>
          <!-- password field -->
          <div class="row">
            <div class="input-field col s12">
              <%= password_field_tag :password %>
              <label for="password">Password</label>
            </div>
          </div>
          <div class="row">
            <div class="col s12 right-align">
              <button class="btn waves-effect waves-light" type="submit">Sign in
              </button>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="modal-footer center-align">
      <p>By signing up you agree to our Terms of Use and Privacy Policy.</p>
    </div>
  </div>
</section>