config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only:[:create, :destroy]

  resources :charges

  resources :users

  resources :users do
    get '/login', to: 'users#login_test' # delete this before deployment
  end
# test index for cookie testing
get '/cookie', to: 'carts#cookie', as: 'cookie'

  resources :carts do 
    patch '/email_preferences', to: 'carts#email_preferences', as: 'email_preferences'
    patch '/text_preferences', to: 'carts#text_preferences', as: 'text_preferences'
  end




  

  namespace :carts do
    scope '/:cart_id' do
      # resource :products, only:[:new, :create]
      resources :products
      delete '/remove/:id', to: 'users#remove', as: 'remove_user'
      post '/invite', to: 'users#invite', as: 'invite_user'
    end

  end

  # resources :products

  get '/invite/:key', to: 'carts#invite', as: 'carts_invite'

  post 'refunds', to: 'refunds#create', as: 'refunds'

  # api
  namespace :api do
    resources :charges, only: [:create]
    resources :carts, only: [:index, :create, :invite, :show, :destroy] do 
      post '/users/invite', to: 'carts/users#invite'
    end
    resources :users, only: [:create]
  end

  post '/api/charges', to: 'charges#create'
  post '/api/carts/:id/products', to: 'api/carts/products#create'
  get 'api/carts/token/:token', to: 'api/carts#index'
  get '/api/carts/:id/:token', to:'api/carts#show'

  resources :sessions, only:[:create, :destroy]

  get 'auth/:provider/callback', to: 'omniauth_sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  # admin
  namespace :admin do
    resources :users
    resources :carts, only:[:index]
    resources :charges
  end

  root to: 'users#index'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :status

  has_many :cart_roles
  has_many :users, through: :cart_roles
  has_many :roles, through: :cart_roles
  has_many :payments
  has_many :products
  has_many :notifications

  has_many :refunds, through: :payments


  validates :name, presence: true
  # validates :minimum_payment, :numericality => true 
  validate :expiry_date_must_be_in_the_future
  

  def expiry_date_must_be_in_the_future 
    errors.add(:expiry, "must be in the future") if !expiry.blank? and expiry < Date.today
  end

  def total
    products.sum("price * quantity")
  end

  def total_payment
    # total = Payment.joins("LEFT JOIN refunds ON refunds.payment_id = payments.id WHERE refunds.payment_id IS NULL AND payments.cart_id = ?", id)
    total = Payment.includes(:refund).where(refunds: { payment_id: nil }).where("payments.cart_id = ?", id).sum(:amount)
    total == 0 ? 0 : total
  end

  def progress
    total == 0 ? 0 : ((total_payment.to_f / total.to_f) * 100).ceil
  end

  def find_role(role_id, medium)
    User.joins(:cart_roles).where('cart_roles.cart_id' => @cart_id, 'cart_roles.role_id' => role_id, "cart_roles.#{medium}_notifications" => true )  
  end

  def organizer
    User.joins(:cart_roles).find_by(cart_roles: {cart_id: id, role_id: 1})
  end

  def thumb_img 
    products.select{ |product| !product.image.nil? }.map{ |product| product.image }
  end

  def check_status
    @cart = self
    organizer_email = find_role(1, "email")
    contributor_email = find_role(2, "email")

    organizer_text = find_role(1, "text")
    contributor_text = find_role(2, "text")

    if status.id == 1 && products.size > 0
      update_attribute(:status_id, 2)
    elsif status.id == 2 && progress == 100
      update_attribute(:status_id, 4)
      Notification.create(cart_id: @cart_id, notification_template_id: 3)
      unless contributor_email.empty?
        contributor_email.each do |c|
          cart_complete(organizer_email, c, @cart).deliver_now
        end
      end

      unless contributor_text.empty?
        contributor_text.each do |text|
           $twilio.account.sms.messages.create(
            :from => ENV['COMPANY_PHONE'],
            :to => "+1#{text.number}",
            :body => "#{@cart.name} has reached its goal!!"
          )
        end
      end

    elsif status.id == 2 && progress < 100 && expiry < Date.today
      update_attribute(:status_id, 3)
      Notification.create(cart_id: @cart_id, notification_template_id: 4)
      unless contributor_email.empty?
        contributor_email.each do |c|
          cart_failure(organizer_email, c, @cart).deliver_now
        end
      end
    
      unless contributor_text.empty?
        contributor_text.each do |text|
           $twilio.account.sms.messages.create(
            :from => ENV['COMPANY_PHONE'],
            :to => "+1#{text.number}",
            :body => "#{@cart.name} did not reach its target goal!"
          )
        end
      end

    end
  end

  # def as_json(options={})
  #   super()
  # end

end

app/controllers/admin/carts_controller.rb
class Admin::CartsController < ApplicationController

  before_filter :require_admin

  def index
    @carts = Cart.all
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @carts }
    end
  end

end

app/controllers/api/carts/products_controller.rb
class Api::Carts::ProductsController < ApplicationController

  skip_before_filter :verify_authenticity_token
  protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }

  def create
    @product = Product.new(
      display_name: params[:display_name],
      url: params[:url],
      quantity: params[:quantity],
      cart_id: params[:id]
      )
    if @product.save
      render :json => {success: "#{@product.display_name} was added successfully!"}.to_json, status: 200
    else @product.errors[:external_id].size > 0 || @product.errors[:description].size > 0 || @product.errors[:price].size > 0
      render :json => {error: @product.errors}.to_json, status: 400
    end
  end

  # def update
  #   @product = Product.find(params[:id])

  #   if @product.update_attributes(product_params)
  #     redirect_to cart_path(params[:cart_id])
  #   else
  #     render :edit
  #   end
  # end

  protected

  # def product_params
  #   params.require(:product).permit(
  #     :display_name, :url, :quantity, :cart_id
  #   )
  # end

end

app/controllers/api/carts/users_controller.rb
class Api::Carts::UsersController < ApplicationController
 skip_before_action :verify_authenticity_token

  def current_user
    @current_user ||= User.find(params[:id]) unless params[:id].nil?
  end

 def remove
  @user = User.find(params[:id])
  @cart = Cart.find(params[:cart_id])
  deleted_user = CartRole.find_by(user_id: @user.id, cart_id: @cart.id)
  if deleted_user.destroy
    Notifications.delete_contributor(@user, @cart).deliver_now
    # Do we need to create a notification row for this?
  end
  redirect_to cart_path(@cart)
  end

  def invite
    #THE RIGHT ONE
      @inviter = current_user
      @cart = Cart.find(params[:cart_id])
      @email = params[:email]
      # @emails.each do |key, email|
        Notifications.invite_contributor(@inviter, @cart, @email).deliver_now
        # Do we need to create a notification row for this?
      # end 
      render :json => { message: "Hey buddo, your invitation was sent successfully."}, status: 200
  end

  protected

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/controllers/api/carts_controller.rb
require 'securerandom'

class Api::CartsController < Api::BaseController

  include CartsHelper

  skip_before_action :require_login, only: [:invite]

  def index
    @current_user = User.find(params[:token])
    @carts = @current_user.carts.where("status_id = 1 OR status_id = 2").order(created_at: :desc)
    render :json => {
      user: @current_user,
      carts: @carts.as_json(methods: [:progress, :total, :total_payment, :organizer, :thumb_img], include: [:products, :status])
    }
  end

  def create
    @current_user = User.find(params[:user_id])
    @cart = Cart.new(
     name: params[:name], 
     expiry: params[:expiry], 
     street_address: params[:street_address], 
     street_address2: params[:street_address2], 
     country: params[:country], 
     city: params[:city], 
     province: params[:province], 
     zip_code: params[:zip_code]
    )
    @cart.status_id = 1
    @cart.key = SecureRandom.uuid
    if @cart.save
      update_user_address(@current_user, params)
      @current_user.cart_roles.create(user_id: @current_user.id, cart_id: @cart.id, role_id: 1)
      params[:cart_id] = @cart.id

      render :json => {
        :cart => @cart
        }
    else
      render :json => {errors: "There was a problem while creating your cart."}.to_json, status: 400
    end
  end

  def invite
    # @user = User.new
    @cart = Cart.find_by(key: params[:key])
    # @cart_array = @cart.cart_roles.map do |c|
    #   c.user_id
    # end
    @email = params[:email]

    render :json => {
      cart: @cart.as_json(methods: [:progress, :total, :total_payment], include: [:products, :users])
    }
  end



  def show
    @contributors = []
    @cart = Cart.find(params[:id])
    @cart.check_status
    session[:cart_id] = @cart.id
    @cart_payments = get_cart_payments(@cart.id)
    @paying_contributors = Payment.where(cart_id: @cart.id).joins(:user)
    @cart_refunds = Refund.where(cart_id: @cart.id).sum(:amount)

    # Sorts through those users to find which users belong to your current cart
    @contributors = CartRole.where(cart_id: @cart.id).uniq
    # Query all the products in the cart from Amazon
    @products = @cart.products
    @goal = @cart.total

    @contributors = @cart.users.where('cart_roles.cart_id' => @cart.id, 'cart_roles.role_id' => 2)
    # Query all the products in the cart
    @products = @cart.products
    
    if (@goal - @cart.total_payment) < 0
      @remaining_balance = 0
    else
      @remaining_balance = (@goal - @cart.total_payment)
    end
    
    if @cart.custom_minimum_payment.nil?
      if @products.length == 0
        @minimum_payment = 0
      else 
        @minimum_payment = (@remaining_balance / (@contributors.length + 1 - @cart_payments.length))
      end
    else
      @minimum_payment = @cart.custom_minimum_payment
    end

    @cart_payees = get_cart_payments(@cart.id)
    @cart_refunds = Refund.where(cart_id: @cart.id).sum(:amount)
    @progress = @cart.progress
    @cart_payments = @cart.total_payment
    @users_and_roles = @contributors.map do |contributor|
      contributor.roles.find_by('cart_roles.cart_id'=> @cart.id)
    end

    # @cart.cart_roles.each do |c|
    #   if current_user.id == c.user_id
    #     render 'show' and return
    #   end
    # end
    
    render :json => {
      cart: @cart.as_json(methods: [:progress, :total, :total_payment], include: [:products, :status, :users, :payments => { include: :user }]),
      organizer: @cart.organizer,
      contributors: @contributors,
      custom_minimum_payment: @minimum_payment,
      remaining_balance: @remaining_balance,
      current_user: User.find(params[:token])
    }
  end


   def destroy
    # SET THIS IN THE AJAX CALL PLEASE
    @cart = Cart.find(params[:cart_id])
    # instead of destroying the cart, we 'archive' it
    @cart.update(status_id: 6)

    contributor_email = find_role(2, "email")
    unless contributor_email.empty?
      contributor_email.each do |c| 
        Notifications.cart_deleted(c, @cart).deliver_now unless contributor_email.empty?
      end
    Notification.create(cart_id: @cart_id, notification_template_id: 2)
    end

    contributor_text = find_role(2, "text")
    unless contributor_text.empty?
      contributor_text.each do |text| 
        $twilio.account.sms.messages.create(
          :from => ENV['COMPANY_PHONE'],
          :to => "+1#{text.number}",
          :body => "The organizer for #{@cart.name} has deleted your cart. All payments will be refunded."
        )
      end
    end
   render :json => {
      cart: @cart.as_json(include: :status)
    }
  end

  def update
    @cart = Cart.find(session[:cart_id])
    @cart.update(custom_minimum_payment: convert_to_cents(update_cart_params[:custom_minimum_payment]))
    @cart.save

    render :json => {
      cart: @cart
    }
  end

  protected


  # def cart_params
  #   params.require(:cart).permit(
  #     :name, :expiry, :street_address, :street_address2, :country, :city, :province, :zip_code
  #   )
  # end

end

app/controllers/cart/products_controller.rb
class Cart::ProductsController < ApplicationController
  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    @product.external_id = /\/(dp|gp\/product)\/(.+)\//.match(@product.url)[2].to_s

    if @product.save
      redirect_to cart_path(params[:product][:cart_id]), notice: "#{@product.display_name} was added successfully!"
    else
      render :new
    end
  end

  def update
  end

  def destroy
    @product = Product.destroy(params[:id])
    redirect_to cart_path(params[:cart_id])
  end

  protected

  def product_params
    params.require(:product).permit(
      :display_name, :url, :quantity, :cart_id
    )
  end

end

app/controllers/carts/products_controller.rb
class Carts::ProductsController < ApplicationController
  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to cart_path(params[:cart_id]), notice: "#{@product.display_name} was added successfully!"
    elsif @product.errors[:external_id].size > 0 || @product.errors[:description].size > 0 || @product.errors[:price].size > 0
      render :new_full
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update_attributes(product_params)
      redirect_to cart_path(params[:cart_id])
    else
      render :edit
    end
  end

  def destroy
    @product = Product.destroy(params[:id])
    redirect_to cart_path(params[:cart_id])
  end

  protected

  def product_params
    params.require(:product).permit(
      :display_name, :url, :quantity, :cart_id, :price, :price_checked_at, :description, :image
    )
  end

end

app/controllers/carts/users_controller.rb
class Carts::UsersController < ApplicationController
 skip_before_action :verify_authenticity_token


 def remove
  @user = User.find(params[:id])
  @cart = Cart.find(params[:cart_id])
  deleted_user = CartRole.find_by(user_id: @user.id, cart_id: @cart.id)
  if deleted_user.destroy
    Notifications.delete_contributor(@user, @cart).deliver_now
    # Do we need to create a notification row for this?
  end
  redirect_to cart_path(@cart)
  end

  def invite
      @inviter = current_user
      @cart = Cart.find(params[:cart_id])
      @email = params[:email]
      # @emails.each do |key, email|
        Notifications.invite_contributor(@inviter, @cart, @email).deliver_now
        # Do we need to create a notification row for this?
      # end 
      render :json => { message: "Hey #{@inviter.name}, your invitation to #{@email} was sent successfully."}, status: 200
  end

  protected

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/controllers/carts_controller.rb
require 'securerandom'

class CartsController < ApplicationController
  
  include CartsHelper

  skip_before_action :require_login, only: [:invite]

  # def index
  # end

  # def new
  #   @cart = Cart.new
  # end

  def email_preferences 
    @cart = Cart.find(session[:cart_id])
    session[:cart_id] = nil
    @cart_role = CartRole.find_by(user_id: current_user.id, cart_id: params[:cart_id])
    @cart_role.email_notifications = !!(params[:email_notifications])
    @cart_role.save
    redirect_to cart_path(@cart)
  end

  def text_preferences 
    @cart = Cart.find(session[:cart_id])
    session[:cart_id] = nil
    @cart_role = CartRole.find_by(user_id: current_user.id, cart_id: params[:cart_id])
    @cart_role.text_notifications = !!(params[:text_notifications]) 
    @cart_role.save
    redirect_to cart_path(@cart)
  end  

  def cookie
    @user = User.new
  end

  def invite
    # @user = User.new
    @cart = Cart.find_by(key: params[:key])
    session[:key] = @cart.id
    # @cart_array = @cart.cart_roles.map do |c|
    #   c.user_id
    # end
    @email = params[:email]
    redirect_to root_path
  end


  protected 

  def cart_params
    params.require(:cart).permit(
      :name, :expiry, :street_address, :street_address2, :country, :city, :province, :zip_code
    )
  end

  def update_cart_params
    params.require(:cart).permit(
      :custom_minimum_payment
    )
  end


  private

  def require_login
    unless current_user
      session[:key] = params[:key]
      #Display error message
      redirect_to root_path
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper

  #defines the percentage of the goal that the cart
  #is currently at
  # def cart_progress(total_paid, goal)
  #   return 0 if goal == 0
  #   ((total_paid.to_f / goal.to_f) * 100).ceil
  # end

  def get_cart_payments(id)
    payments = Payment.where(cart_id: id)
    payments.select { | payment | payment.refund == nil }
  end

  # def calculate_total_payments(array)
  #   values = array.map(&:amount)
  #   values.inject(0){ |sum,x| sum + x }
  # end


  def update_user_address(current_user, user_params)
    current_user.update(street_address: user_params["cart"]["street_address"], 
                        street_address2: user_params["cart"]["street_address2"],
                        country: user_params["cart"]["country"],
                        city: user_params["cart"]["city"],
                        province: user_params["cart"]["province"],
                        zip_code: user_params["cart"]["zip_code"],
                        )
    current_user.save
  end

end

app/views/carts/_contributor.html.erb
<%= payment.user.name %> paid <%= format_price(payment.amount) %>

app/views/carts/_invitations.html.erb
<button data-key= <%= @cart.key %> class="FBInvite">Invite through Facebook</button>

<p> Invite your friends through email! Separate multiple emails with commas</p>
<%= form_tag carts_invite_user_path(@cart) do %>
  <%= render 'email_invites' %>
<% end %>

app/views/carts/_notification_prefererences.html.erb
  <% if current_user.email %>
   <%= form_tag cart_email_preferences_path(@cart), method: :patch do %>
    <%= label_tag :email_notifications, "Email me for product milestones!" %>

      <% if user_notifications(current_user, @cart).email_notifications %>
        <%= check_box_tag :email_notifications, 1, {checked: true} %>
      <% else %>
        <%= check_box_tag :email_notifications, 2, false %>
      <% end %>    
    <%= submit_tag "Submit" %>
    <% end %>
  <% else %>
    <%= form_for current_user do |f| %>
      <%= f.label :email %>
      <%= f.text_field :email %>
      <%= f.submit %>
    <% end %> 
  <% end %>
 

 <% if current_user.number %>
   <%= form_tag cart_text_preferences_path(@cart), method: :patch do %>
    <%= label_tag :text_notifications, "Text me for product milestones!" %>

      <% if user_notifications(current_user, @cart).text_notifications %>
        <%= check_box_tag :text_notifications, 1, {checked: true} %>
      <% else %>
        <%= check_box_tag :text_notifications, 2, false %>
      <% end %>
    <%= submit_tag "Submit" %>
    <% end %>
  <% else %>
    <%= form_for current_user do |f| %>
      <%= f.label :number %>
      <%= f.text_field :number %>
      <%= f.submit %>
    <% end %> 
  <% end %>

app/views/carts/_products.html.erb
<div id="products">
  <% if @products.size == 0 %>
    <div class="cart-options">
      <p>This cart doesn't have a product yet.</p>
      <a href="<%= new_carts_product_path(@cart) %>" class="btn-rect btn-primary waves-effect waves-light  modal-trigger">Add Product</a>
    </div>
  <% else %>
    <ul id="product-list" class="collection">

    <% @products.each do |product| %>
      <li class="collection-item avatar product-item">
        <% if product.image.nil? %>
          <a target="_blank" href="<%= product.url %>">
            <i class="material-icons circle green">insert_chart</i>
          </a>
        <% else %>
          <a target="_blank" href="<%= product.url %>">
            <img src="<%= product.image %>" alt="" class="circle">
          </a>
        <% end %>
        <h5><%= product.display_name %></h5>
        <p><%= format_price(product.price) %> x <%= product.quantity %></p>
        <p><!-- product.description --></p>

        <% if @cart.organizer.id == current_user.id %> 
        <p class="product-ops"><%= link_to 'Edit', edit_carts_product_path(@cart, product) %> | <%= link_to 'Remove', carts_product_path(@cart, product), data: {:confirm => 'Are you sure?'}, :method => :delete  %></p>
        <% end %>
        <a href="<%= product.url %>" target="_blank" class="secondary-content"><i class="material-icons">open_in_new</i></a>
      </li>
    <% end %>
    </ul>
    <a href="<%= new_carts_product_path(@cart) %>"><i class="material-icons">add_circle</i> Add product</a>
  <% end %>
</div>

app/views/carts/index.html.erb
<div class="row user-greeting">
  <div class="col s12 center-align toucan-bg">
    <div></div>
    <h1>Ahoy, <%= current_user.name %>!</h1>
  </div>
</div>

<div class="container">
  <div class="row">
    <ul class="col s12 cart-list">
        <!-- the loop -->
        <% if current_user && @carts.size > 0 %>
          <% @carts.each do |cart|  %>
            <li class="col s12">
              <%= render 'list_carts', cart: cart %>
            </li>
          <% end %>
        <% end %>
    </ul>
  </div>
</div>
  
<a href="<%= new_cart_path %>" class="btn-floating btn-large waves-effect waves-light pink modal-trigger" id="new-cart-btn"><i class="material-icons">add</i></a>


<!-- render 'new_cart' -->

app/views/carts/new.html.erb
<h1>Build a new cart</h1>

<%= form_for @cart, url: carts_path(@cart) do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %> 
  <br>
  <br>
  <%= f.label "Due Date" %><br>
  <%= f.date_field :expiry %>
  <br>
  <br>
  <%= f.label :street_address %><br>
  <%= f.text_field :street_address, placeholder: current_user.street_address %><br>
  <%= f.text_field :street_address2, placeholder: current_user.street_address2 %>
  <br>
  <br>
  <%= f.label :country %><br>
  <%= f.text_field :country, placeholder: current_user.country %>
  <br>
  <br>
  <%= f.label :city %><br>
  <%= f.text_field :city, placeholder: current_user.city %>
  <br>
  <%= f.label :province %><br>
  <%= f.text_field :province, placeholder: current_user.province %>
  <br>
  <%= f.label :zip_code %><br>
  <%= f.text_field :zip_code, placeholder: current_user.zip_code %><br>
  <%= f.submit "Submit" %>
<% end %>

app/views/carts/show.html.erb
<div class="container">
  <!-- top section -->
  <div class="row" id="cart-top">
    <div class="col s12 m8">
      <div class="cart-header">
        <h2><%= @cart.name %></h2>
        <div class="chip"><%= @cart.status.text %></div>
      </div>
      
      <div class="cart-meta">
        <div class="cart-submeta">
          <h4><%= @contributors.size %></h4>
          <span>contributers</span>
        </div>

        <div class="cart-submeta">
          <h4>5</h4>
          <span>days to go</span>
        </div>

        <div class="cart-submeta">
          <h4><%= format_price(@cart.total_payment) %></h4>
          <span>collected</span>
        </div>

        <div class="progress">
          <div class="determinate" style="<%= "width: #{@cart.progress}%" %>"></div>
        </div>
        <div><span><%= "#{@cart.progress}\% of #{format_price(@cart.total)} goal" %></span></div>
      </div>
    </div>
    <div class="col s12 m4">
      <div class="cart-options">
        <a href="#payment-modal" class="btn-rect btn-primary waves-effect waves-light  modal-trigger">Contribute Now</a>
        <% if @cart.organizer.id == current_user.id %>
          <a class="btn-rect btn-secondary" data-confirm="Are you sure?" data-title="WARNING!" rel="nofollow" data-method="delete" href="<%= cart_path(@cart) %>">
            Cancel
          </a>
        <% end %>
      </div>


      <ul id="cart-options">
        <li>
          <a href="#invite-modal" class=" modal-trigger">
            <i class="material-icons">group_add</i>
            Share
          </a>
        </li>
        <li>
          <a href="#notification-modal" class=" modal-trigger">
            <i class="material-icons">notifications</i>
            Notifications
          </a>
        </li>
        <li>
          
        </li>
      </ul>

      

      <!-- <div><h4><%= format_price(@cart.total) %></h4></div> -->
      
    </div>
  </div>

  <!-- bottom section -->
  <div class="row"  id="cart-bottom">
    <div class="col s12 m8">
      <ul class="tabs">
        <li class="tab col s3"><a class="active" href="#products">Products</a></li>
        <li class="tab col s3"><a href="#payments">Payments</a></li>
      </ul>
      <!-- list of product -->
      <%= render 'products' %>
      <!-- list of payment -->
      <div id="payments" class="col s12">
        <% if @cart_payments.size > 0 %>
          <% @cart_payments.each do |payment| %>
            <div class="payment-entry row">
              <div class="col s2 avatar">
                <img src="http://placehold.it/150?text=%20" class="circle">
              </div>
              <div class="col s10 payment-detail">
                <div class="payee"><%= payment.user.name %></div>
                <span title=""><%= format_price(payment.amount) %></span>
              </div>
            </div>
          <% end %>
        <% else %>
          <div class="cart-options">
            <p>No one's contributed yet.</p>
            <a href="#payment-modal" class="btn-rect btn-primary waves-effect waves-light  modal-trigger">Contribute Now</a>
          </div>
        <% end %>

      </div>
    </div>

    <div class="col s12 m4 center-align" id="contribution">
      <div><span class="tab-label">Contributors</span></div>
      
      <div id="contributors" class="col s12">
        <% if @contributors.size > 0 %>
          <% @contributors.each do |user| %>
            <div class="chip">
              <img src="http://placehold.it/150?text=%20">
              <span><%= user.name %></span>
            </div>
          <% end %>
          <a href="#invite-modal" class="modal-trigger">Invites more friends</a>
        <% else %>
          <a href="#invite-modal" class="modal-trigger">Invites your friends</a>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!-- invite modal -->
<div id="invite-modal" class="modal">
  <div class="modal-header center-align">
    <h4>Invite Your Friends</h4>
    <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat"><i class="material-icons">clear</i></a>
  </div>
  <div class="modal-content center-align">
    <button class="btn btn-facebook waves-effect waves-light FBInvite" type="submit" name="action" data-key= <%= @cart.key %> >
      <i class="material-icons left">send</i> Share with your Facebook friends
    </button>
  </div>
  <div class="modal-content">
    <div class="center-align">
      OR
    </div>
    <div class="row">
      <!-- <form class="col s12"> -->
      <%= form_tag carts_invite_user_path(@cart), class: "col s12" do %>
        <!-- email field -->
        <div class="row">
          <div class="input-field col s12">
            <input id="email" type="text" class="validate">
            <label for="email">Email</label>
          </div>
        </div>
        <!-- submit -->
        <div class="row">
          <div class="col s12 right-align">
            <button class="btn waves-effect waves-light" type="submit" name="action">Send
            </button>
          </div>
        </div>
      <!-- </form> -->
      <% end %>
    </div>
  </div>
</div>

<!-- notification modal -->
<div id="notification-modal" class="modal">
  <div class="modal-header center-align">
    <h4>Notification Settings</h4>
    <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat"><i class="material-icons">clear</i></a>
  </div>
  
  <div class="modal-content">
    <div class="row">
      <!-- <form class="col s12"> -->
      <%= form_tag carts_invite_user_path(@cart), class: "col s12" do %>
        <!-- email field -->
        <div class="row">
          <div class="input-field col s12">
            <input id="email" type="text" class="validate">
            <label for="email">Email</label>
          </div>
        </div>
        <!-- submit -->
        <div class="row">
          <div class="col s12 right-align">
            <button class="btn waves-effect waves-light" type="submit" name="action">Save
            </button>
          </div>
        </div>
      <!-- </form> -->
      <% end %>
    </div>
  </div>
</div>

<br>
<br>
<br>
<br>