config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only:[:create, :destroy]

  resources :charges

  resources :users

  resources :users do
    get '/login', to: 'users#login_test' # delete this before deployment
  end
# test index for cookie testing
get '/cookie', to: 'carts#cookie', as: 'cookie'

  resources :carts do 
    patch '/email_preferences', to: 'carts#email_preferences', as: 'email_preferences'
    patch '/text_preferences', to: 'carts#text_preferences', as: 'text_preferences'
  end




  

  namespace :carts do
    scope '/:cart_id' do
      # resource :products, only:[:new, :create]
      resources :products
      delete '/remove/:id', to: 'users#remove', as: 'remove_user'
      post '/invite', to: 'users#invite', as: 'invite_user'
    end

  end

  # resources :products

  get '/invite/:key', to: 'carts#invite', as: 'carts_invite'

  post 'refunds', to: 'refunds#create', as: 'refunds'

  # api
  namespace :api do
    resources :charges, only: [:create]
    resources :carts, only: [:index, :create, :invite, :show, :destroy] do 
      post '/users/invite', to: 'carts/users#invite'
    end
    resources :users, only: [:create]
  end

  post '/api/charges', to: 'charges#create'
  post '/api/carts/:id/products', to: 'api/carts/products#create'
  get 'api/carts/token/:token', to: 'api/carts#index'
  get '/api/carts/:id/:token', to:'api/carts#show'

  resources :sessions, only:[:create, :destroy]

  get 'auth/:provider/callback', to: 'omniauth_sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  # admin
  namespace :admin do
    resources :users
    resources :carts, only:[:index]
    resources :charges
  end

  root to: 'users#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :cart_roles
  has_many :carts, through: :cart_roles
  has_many :roles, through: :cart_roles
  has_many :payments
  has_many :refunds, through: :payments


  validates :name, presence: true
  # validates :email, presence: true, length: { minimum: 5 }
  validates :password, presence: true, length: { minimum: 8 }, on: :update, allow_blank: true

  has_secure_password


  def self.from_omniauth(auth)
    where(uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.email = auth.info.email
      user.image = auth.info.image
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.password = SecureRandom.uuid.to_s
      user.oauth_expires_at = auth.credentials.expires_at.nil? ? 7 : Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_filter :require_admin

  def index
    @users = User.all
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @users }
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_users_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to admin_users_path
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
  end

  protected

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/controllers/api/carts/users_controller.rb
class Api::Carts::UsersController < ApplicationController
 skip_before_action :verify_authenticity_token

  def current_user
    @current_user ||= User.find(params[:id]) unless params[:id].nil?
  end

 def remove
  @user = User.find(params[:id])
  @cart = Cart.find(params[:cart_id])
  deleted_user = CartRole.find_by(user_id: @user.id, cart_id: @cart.id)
  if deleted_user.destroy
    Notifications.delete_contributor(@user, @cart).deliver_now
    # Do we need to create a notification row for this?
  end
  redirect_to cart_path(@cart)
  end

  def invite
    #THE RIGHT ONE
      @inviter = current_user
      @cart = Cart.find(params[:cart_id])
      @email = params[:email]
      # @emails.each do |key, email|
        Notifications.invite_contributor(@inviter, @cart, @email).deliver_now
        # Do we need to create a notification row for this?
      # end 
      render :json => { message: "Hey buddo, your invitation was sent successfully."}, status: 200
  end

  protected

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/controllers/api/users_controller.rb
class UsersController < ApplicationController

  def update
    # @cart = Cart.find(session[:cart_id])
    @user = CartRole.find_by(user_id: params[:user_id], cart_id: params[:cart_id])
    # @user.password = SecureRandom.uuid
    @user.update_attributes()
    if @user.save
      # @cart = Cart.find(session[:cart_id])
      render :json => {
        user: @user.as_json(include: :carts)
      }
    else

    end
  end

end

app/controllers/carts/users_controller.rb
class Carts::UsersController < ApplicationController
 skip_before_action :verify_authenticity_token


 def remove
  @user = User.find(params[:id])
  @cart = Cart.find(params[:cart_id])
  deleted_user = CartRole.find_by(user_id: @user.id, cart_id: @cart.id)
  if deleted_user.destroy
    Notifications.delete_contributor(@user, @cart).deliver_now
    # Do we need to create a notification row for this?
  end
  redirect_to cart_path(@cart)
  end

  def invite
      @inviter = current_user
      @cart = Cart.find(params[:cart_id])
      @email = params[:email]
      # @emails.each do |key, email|
        Notifications.invite_contributor(@inviter, @cart, @email).deliver_now
        # Do we need to create a notification row for this?
      # end 
      render :json => { message: "Hey #{@inviter.name}, your invitation to #{@email} was sent successfully."}, status: 200
  end

  protected

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/controllers/users_controller.rb
require 'securerandom'
class UsersController < ApplicationController
  def index
    @user = User.new
    render :index
  end

  def create
    @user = User.new(user_params)
    if @user.save 
      Notifications.welcome_email(@user).deliver_now
            if session[:key]
        key = session[:key]
        session[:key] = nil
        CartRole.create(user_id: @user.id, cart_id: key, role_id: 2, email_notifications: true, text_notifications: true)
        # Will only redirect users to the invite page IF that is how 
        # they reached the site in the first place

        redirect_to "http://localhost:3000/dashboard/?token=#{@user.id}"
      else
        redirect_to "http://localhost:3000/dashboard/?token=#{@user.id}"
      end
    else
      redirect_to root_path
    end
  end


  def destroy
  end

  def login_test
    cookies[:user_name] = User.find(params[:user_id]).name
    cookies[:user_id] = params[:user_id]
    session[:user_id] = params[:user_id]
    redirect_to "http://localhost:3000/dashboard?token=#{params[:user_id]}"
  end



  protected

  def user_params
    params.require(:user).permit("name", "email", "password", "number")
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.label :final_boss %>&nbsp;<%= f.check_box :final_boss %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/admin/users/edit.html.erb
<h2><%= link_to 'Back', admin_users_path %></h2>

<h1>Edit User</h1>
<%= render 'form' %>

app/views/admin/users/index.html.erb
<h1>Admin User Management</h1>
<div><%= link_to "New user", new_admin_user_path %></div>
<hr>
<% @users.each do |user| %>
  <p><%= user.name %> - <%= user.email %> | 
    <%= link_to "view", admin_user_path(user) %> | 
    <%= link_to "edit", edit_admin_user_path(user) %> | 
    <%= link_to "delete", admin_user_path(user), method: :delete, data: {confirm: "You sure?", test: "1"} %>
  </p>
  <hr>
<% end %>

app/views/admin/users/new.html.erb
<h2><%= link_to 'Back', admin_users_path %></h2>

<h1>New User</h1>
<%= render 'form' %>

app/views/admin/users/show.html.erb
<h2><%= link_to 'Back', admin_users_path %></h2>

<h1><%= @user.name %></h1>
<h3><%= @user.email %></h3>
<hr>
<h2>Carts</h2>
<% if @user.carts.size > 0 %>
  <% @user.carts.each do |cart| %>
    <li><%= link_to cart.name, cart_path(cart) %></li>
  <% end %>
<% else %>
  <li>No cart</li>
<% end %>
<hr>
<h2>Payments</h2>
<% if @user.payments.size > 0 %>
  <% @user.payments.each do |payment| %>
    <li><%= "Cart: #{payment.cart.name} Amount: #{format_price(payment.amount)}" %></li>
  <% end %>
<% else %>
  <li>No payment</li>
<% end %>